name: sos_alert_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^19.1.0
  flutter_contacts: ^1.1.9+2
  flutter_sms: ^2.3.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
